version: "3.7"

networks:
    default-network:
        name: laravel-network
        driver: bridge

services:
    app:
        build:
            context: .
            args:
                - TZ=${TZ}
        container_name: laravel-app
        volumes:
            - .:/work
            - ./docker/logs/php:/var/log/php
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /work
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - TZ=${TZ}
        networks:
            - default-network

    web:
        image: nginx:1.17-alpine
        container_name: laravel-nginx
        depends_on:
            - app
        ports:
            - ${NGINX_PORT}:8000
        volumes:
            - .:/work
            - ./docker/logs/nginx:/var/log/nginx
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        environment:
            - TZ=${TZ}
        networks:
            - default-network

    db:
        image: mysql:5.7
        container_name: laravel-mysql
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - laravel-db-store:/var/lib/mysql
            - ./docker/logs/mysql:/var/log/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - TZ=${TZ}
        networks:
            - default-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2.1
        container_name: laravel-phpmyadmin
        depends_on:
            - db
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - default-network

    cron:
        build:
            context: .
            args:
                - TZ=${TZ}
        container_name: laravel-cron
        volumes:
            - .:/work
            - ./docker/logs/php:/var/log/php
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /work
        entrypoint: >
            sh -c "echo '* * * * * php /work/artisan schedule:run >> /work/docker/logs/cron/cron.log 2>&1' | crontab - &&
                   crond -f -d 8"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - TZ=${TZ}
        networks:
            - default-network

volumes:
    laravel-db-store:
        driver: local
